name: paleots
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.21.0
  - jupyter
  - xarray
  - netCDF4
  - Bottleneck
  - dask
  - climlab
  - pip
  - python=3.10
  - pip:
    - pyleoclim
    - git+https://github.com/LinkedEarth/pylipd.git@main
    - pymannkendall
    - kneed
